package io.academicmonitor.communication.application;

public enum CommunicationWorkflowError {
    ALERT_NOT_FOUND,
    ALERT_NOT_ACTIVE,
    RECIPIENT_NOT_FOUND,
    RECIPIENT_AMBIGUOUS,
    RECIPIENT_NOT_REACHABLE,
    COMMUNICATION_NOT_FOUND,
    COMMUNICATION_ALREADY_SENT,
    COMMUNICATION_NOT_EDITABLE,
    COMMUNICATION_NOT_SENDABLE,
    STUDENT_OUT_OF_SCOPE
}
